name: ponto_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  logger: ^1.1.0
  flutter_screenutil: ^5.6.0
  awesome_notifications_fcm: ^0.7.4+1
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.2
  font_awesome_flutter: ^10.2.1
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  firebase_messaging: ^14.1.0
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2
  encrypted_shared_preferences: ^3.0.1
  go_router: ^5.1.5
  dio: ^4.0.6
  intl: ^0.17.0
  faker: ^2.0.0
  get: ^4.6.5
  path_provider: ^2.0.11
  cloud_firestore: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  objectbox_generator: ^1.6.2
  mockito: ^5.3.2

flutter:
  uses-material-design: true































